using FunBooksAndVideos.Application.Contracts.Responses;
using FunBooksAndVideos.Application.Services;
using Microsoft.AspNetCore.Mvc;

namespace FunBooksAndVideos.Api.Controllers;

/// <summary>Shipping slips generated by BR2.</summary>
[ApiController]
[Route("api/shipping-slips")]
[Produces("application/json")]
public sealed class ShippingSlipsController : ControllerBase
{
    private readonly IShippingSlipService _shippingSlipService;

    public ShippingSlipsController(IShippingSlipService shippingSlipService)
    {
        _shippingSlipService = shippingSlipService;
    }

    /// <summary>Gets a shipping slip by id.</summary>
    [HttpGet("{id:guid}")]
    [ProducesResponseType(typeof(ShippingSlipResponse), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status404NotFound)]
    public async Task<ActionResult<ShippingSlipResponse>> GetById(Guid id, CancellationToken cancellationToken)
    {
        var slip = await _shippingSlipService.GetByIdAsync(id, cancellationToken);
        return slip is null ? NotFound() : Ok(slip);
    }

    /// <summary>Lists the shipping slips generated for a purchase order.</summary>
    [HttpGet("/api/purchase-orders/{purchaseOrderId:int}/shipping-slips")]
    [ProducesResponseType(typeof(IReadOnlyList<ShippingSlipResponse>), StatusCodes.Status200OK)]
    public async Task<ActionResult<IReadOnlyList<ShippingSlipResponse>>> GetByPurchaseOrder(
        int purchaseOrderId, CancellationToken cancellationToken) =>
        Ok(await _shippingSlipService.GetByPurchaseOrderIdAsync(purchaseOrderId, cancellationToken));
}
